spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 31415926
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect